// Generated by BUCKLESCRIPT VERSION 4.0.18, PLEASE EDIT WITH CARE
'use strict';

var ReactDOMRe = require("reason-react/src/ReactDOMRe.js");
var ReasonReact = require("reason-react/src/ReasonReact.js");
var Presentation$ReactTemplate = require("./Presentation.bs.js");

function $$default(param) {
  return ReactDOMRe.renderToElementWithId(ReasonReact.element(undefined, undefined, Presentation$ReactTemplate.make(/* array */[])), "root");
}

exports.$$default = $$default;
exports.default = $$default;
exports.__esModule = true;
/* ReactDOMRe Not a pure module */
