// Generated by BUCKLESCRIPT VERSION 4.0.18, PLEASE EDIT WITH CARE
'use strict';

var $$Array = require("bs-platform/lib/js/array.js");
var React = require("react");
var Js_dict = require("bs-platform/lib/js/js_dict.js");
var Pervasives = require("bs-platform/lib/js/pervasives.js");
var ReactDOMRe = require("reason-react/src/ReactDOMRe.js");
var Caml_option = require("bs-platform/lib/js/caml_option.js");
var ReasonReact = require("reason-react/src/ReasonReact.js");

function s(prim) {
  return prim;
}

var component = ReasonReact.statelessComponent("Presentation");

function make(lang, code, _children) {
  return /* record */[
          /* debugName */component[/* debugName */0],
          /* reactClassInternal */component[/* reactClassInternal */1],
          /* handedOffState */component[/* handedOffState */2],
          /* willReceiveProps */component[/* willReceiveProps */3],
          /* didMount */component[/* didMount */4],
          /* didUpdate */component[/* didUpdate */5],
          /* willUnmount */component[/* willUnmount */6],
          /* willUpdate */component[/* willUpdate */7],
          /* shouldUpdate */component[/* shouldUpdate */8],
          /* render */(function (_self) {
              var match = Js_dict.get(window.Prism.languages, lang);
              var language = match !== undefined ? Caml_option.valFromOption(match) : Pervasives.failwith("language not found");
              var wrapLine = function (index, line) {
                return React.createElement("div", {
                            key: String(index),
                            dangerouslySetInnerHTML: {
                              __html: line
                            }
                          });
              };
              var lines = $$Array.mapi(wrapLine, window.Prism.highlight(code, language).split("\n"));
              return ReactDOMRe.createElementVariadic("code", {
                          style: {
                            display: "inline-block",
                            textAlign: "left"
                          }
                        }, lines);
            }),
          /* initialState */component[/* initialState */10],
          /* retainedProps */component[/* retainedProps */11],
          /* reducer */component[/* reducer */12],
          /* jsElementWrapped */component[/* jsElementWrapped */13]
        ];
}

exports.s = s;
exports.component = component;
exports.make = make;
/* component Not a pure module */
