// Generated by BUCKLESCRIPT VERSION 4.0.18, PLEASE EDIT WITH CARE
'use strict';

var SpectacleThemeNova = require("spectacle-theme-nova");

var custom = {
  global: {
    body: {
      background: "white"
    }
  }
};

var t = SpectacleThemeNova.default("avon", custom);

exports.custom = custom;
exports.t = t;
/* t Not a pure module */
